### ISSUE TITLE
[ENH] Add info message about Jupyter notebook server to ENTRYPOINT

### ISSUE THREAD

**Issue by mike-wendt** [rapidsai/docker#120]
https://github.com/rapidsai/docker/blob/23027b8b7b64d6f4f7441956b4facf6f3273bf46/context/.start_jupyter_run_in_rapids.sh#L3

After the line above, I think we should add some instructions for the user to let them know the notebook server has been started and how to access it. Let me know your thoughts on this.

**Comment by aleksficek** [comment]
+1 for this idea, at the very least knowing the notebook server has started can help in future debugging

**Comment by ajschmidt8** [comment]
agree!

**Comment by aleksficek** [comment]
I'll take on this issue

**Comment by rlratzel** [comment]
Here's a minor addition that could help docker users that don't know which ports need to be exposed:
```
Ensure the following args to "docker run" are added to expose the server ports to your host machine:
   -p 8888:8888 -p 8787:8787 -p 8786:8786
```

**Comment by aleksficek** [comment]
> Here's a minor addition that could help docker users that don't know which ports need to be exposed:
> 
> ```
> Ensure the following args to "docker run" are added to expose the server ports to your host machine:
>    -p 8888:8888 -p 8787:8787 -p 8786:8786
> ```

Great idea, I added it and made a new PR up for review https://github.com/rapidsai/docker/pull/124
