### ISSUE TITLE
[FEA] Add interactive config file generator

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/docker#13]
**Is your feature request related to a problem? Please describe.**
Some users may need to be guided more than others when it comes to configuring rapidsdevtool.sh, and the config file may not communicate exctly what needs to be changed for a particular use case well.  

**Describe the solution you'd like**
Something like an interactive mode which "interviewed" a client and generated/updated the config based on common use cases would help.

**Describe alternatives you've considered**
Settings based on "modes" or use cases which were essentially like configuration macros could also help. For example, a config setting that allowed a user to specify a RAPIDS component they were building, like "buildFor=cuDF", and all the other settings were overridden automatically.

**Additional context**
n/a

**Comment by ajschmidt8** [comment]
closing this issue as it no longer appears to be applicable
