### ISSUE TITLE
[BUG] Jupyter cannot block and logs are sent to /dev/null

### ISSUE THREAD

**Issue by jacobtomlinson** [rapidsai/docker#133]
**Describe the bug**

When working on the RAPIDS Helm Chart we have a pod which will be running Jupyter as a daemon. Ideally this pod would simply run Jupyter as the main blocking process.

The current config for the `runtime` image is for Jupyter to be run during the entrypoint with nohup and all stdout/stderr is sent to `/dev/null`.

The default command is `bash` which just exits if the container is not running in interactive mode.

In order for us to block on the Jupyter process we currently have to override the entrypoint and command with a new one which runs Jupyter in the foreground. This results in duplication of the Jupyter startup command in the helm chart. Alternatively we could instead tail the nohup output as the command in order to block, but this isn't possible due to all output going to `/dev/null`.

**Steps/Code to reproduce bug**

```
docker run --rm 0.14-cuda10.1-runtime-ubuntu18.04-py3.7
```

Container just exits.

**Expected behavior**

I would expect to be able to run the container with Jupyter as the foreground process.

A few ways this could be achieved:
- Pipe the output to somewhere like `/var/log/jupyter.log` so that we can override the command as `tail -f /var/log/jupyter.log`
- Run Jupyter in the foreground by default without nohup and output redirection
- Split the `start_jupyter.sh` script into a foreground and background version, allowing us to override the entrypoint/command to the foreground version.

**Environment details (please complete the following information):**
Any
 

**Additional context**
NA

cc @quasiben

**Comment by jacobtomlinson** [comment]
Our current workaround is to override the entry point and command (via the `command:` option in Kubernetes) and the args.

We are basically running the command from `start_jupyter.sh` without nohup and backgrounding. But this is not ideal as any changes to `start_jupyter.sh` wouldn't be applied in the helm chart without a manual sync.

https://github.com/rapidsai/helm-chart/blob/48da21c0b37d73d4cf3b367f13b658bea4e3853c/rapidsai/values.yaml#L93-L96

**Comment by ajschmidt8** [comment]
once the new nightlies are built, you can use the following `docker run` flag to enable `jupyter-lab` to run in the foreground: `-e JUPYTER_FG=true`

**Comment by jacobtomlinson** [comment]
Thanks @ajschmidt8

**Comment by jacobtomlinson** [comment]
Sorry to say I'm seeing this error with the change.

```
/.run_in_rapids: line 12: /dev/tty: No such device or address
```
