### ISSUE TITLE
[FEA] Add openpyxl library to Docker containers to permit export as Excel via Pandas

### ISSUE THREAD

**Issue by MurrayData** [rapidsai/docker#136]
When writing the output of a cudf groupby query to Excel (via Pandas) I got the following:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<timed exec> in <module>

/opt/conda/envs/rapids/lib/python3.6/site-packages/pandas/io/excel/_openpyxl.py in __init__(self, path, engine, mode, **engine_kwargs)
     17     def __init__(self, path, engine=None, mode="w", **engine_kwargs):
     18         # Use the openpyxl module as the Excel writer.
---> 19         from openpyxl.workbook import Workbook
     20 
     21         super().__init__(path, mode=mode, **engine_kwargs)

ModuleNotFoundError: No module named 'openpyxl'
```

As a workaround, I manually added openpyxl with:

```
conda install openpyxl
```

Please can this Pandas dependency be added to future versions of the containers?

**Comment by ajschmidt8** [comment]
@MurrayData , we recently merged #170, which enables `conda`, `pip`, `apt`, and `yum` packages to be installed via environment variables provided to the `docker run` command. Documentation can be found [here on DockerHub](https://hub.docker.com/r/rapidsai/rapidsai-nightly) under the `Usage` section.

I don't think we have plans to add `openpyxl ` to the containers, but this should provide a convenient workaround. Closing this issue, but feel free to post back here if you have any issues with the new feature.
