### ISSUE TITLE
[BUG] cuGraph Force-Atlas2.ipynb can't execute, holoviews not installed in rapidsai:cuda10.2-runtime-ubuntu18.04, possibly others

### ISSUE THREAD

**Issue by bfeeny** [rapidsai/docker#147]
**Describe the bug**
holoviews not installed in rapidsai:cuda10.2-runtime-ubuntu18.04, possibly other builds.
The cuGraph Force-Atlas2.ipynb demo relies on this.

**Steps/Code to reproduce bug**
execute  /rapids/notebooks/cugraph/layout/Force-Atlas2.ipynb

**Expected behavior**
The demo should run with no errors, instead it produces:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-13-cdaa39fc78bd> in <module>
      3 import numpy as np
      4 import pandas as pd
----> 5 import holoviews as hv
      6 
      7 from colorcet import fire

ModuleNotFoundError: No module named 'holoviews'
```
**Environment details (please complete the following information):**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
Docker
 - Method of cuDF install: [conda, Docker, or from source]
NGC rapidsai:cuda10.2-runtime-ubuntu18.04
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used
docker pull nvcr.io/nvidia/rapidsai/rapidsai:cuda10.2-runtime-ubuntu18.04
docker run --gpus all --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786 \
        -v /bulk:/rapids/notebooks/my_data \
        --shm-size=8G \
        rapidsai:cuda10.2-runtime-ubuntu18.04
 - Please run and attach the output of the `cudf/print_env.sh` script to gather relevant environment details
 
[print_env.sh-output.txt](https://github.com/rapidsai/docker/files/5093117/print_env.sh-output.txt)

**Additional context**

**Comment by msadang** [comment]
Hi.  holoviews has been included in the repo.  This should close out this ticket.
