### ISSUE TITLE
[BUG] Demonstration Notebook missing requirements

### ISSUE THREAD

**Issue by Data-drone** [rapidsai/docker#157]
**Describe the bug**
Periodicity_Detection requires s3fs which isn't included 

**Steps/Code to reproduce bug**
Follow the Docker cuda setup commands then try to run the periodicity detection notebook

    docker pull rapidsai/rapidsai:cuda10.2-runtime-ubuntu18.04-py3.8
    docker run --gpus all --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786 \
        rapidsai/rapidsai:cuda10.2-runtime-ubuntu18.04-py3.8

**Expected behavior**
The notebook should be able to be run full. Or a `requirements.txt` of some sort should be provided for each notebook with instructions on install

**Environment details (please complete the following information):**
 - Environment location: Docker
 - Method of cuDF install: See above 

`pip install s3fs` fixes it but either it should be bundled or there should be a requirements.txt?

**Comment by msadang** [comment]
Hi.  s3fs has been included in the repo.  This should close out this ticket.
