### ISSUE TITLE
Add Lincense file to the repo

### ISSUE THREAD

**Issue by peterableda** [rapidsai/docker#159]
We are considering building on top of rapidsai Docker images but getting held back on license review. Can you upload a license file to this git repo? Cuda is using BSD 3-Clause licenses for its Dockerfile repo, can you use the same?
https://gitlab.com/nvidia/container-images/cuda/-/blob/master/LICENSE

**Comment by ajschmidt8** [comment]
@peterableda, thanks for pointing this out. Fixed in #161
