### ISSUE TITLE
[DOC] Missing Usage Document for Ports

### ISSUE THREAD

**Issue by znmeb** [rapidsai/docker#174]
## Report needed documentation

**Report needed documentation**
Reference: <https://hub.docker.com/r/rapidsai/rapidsai-dev>, `Usage` section

The running container exposes ports 8787 and 8786, according to the `Dockerfile`. And the `docker run` command binds those ports to `localhost`. But there's no information on how to use those ports. Is anything even listening on them? Are there servers on the image that can be started?

I did an `apt update && apt install mlocate && updatedb && locate rstudio`, since the RStudio Server conventionally listens on port 8787. But it's not there.

**Describe the documentation you'd like**
If there's nothing listening on those ports, delete them from the `docker run` command. If there is something listening, document how to use it.

**Comment by ajschmidt8** [comment]
@znmeb, thank you for reporting this. The missing documentation has been added in #195 for release `0.16`. The DockerHub readmes will be updated once the release is complete.

Here's a list of all of the ports used by our `runtime` and `devel` containers:

- `8888` - exposes a [JupyterLab](https://jupyterlab.readthedocs.io/en/stable/) notebook server
- `8786` - exposes a [Dask](https://docs.dask.org/en/latest/) scheduler
- `8787` - exposes a Dask [diagnostic web server](https://docs.dask.org/en/latest/setup/cli.html#diagnostic-web-servers)
