### ISSUE TITLE
[BUG] RAPIDS devel image has broken PATH for building RAPIDS libs (cannot find nvcc)

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/docker#182]
If a user tries to run a typical build of a RAPIDS library (cugraph in my case) using a `devel` image, their build errors with this message:
```
    ccache: error: Could not find compiler "nvcc" in PATH
```
I believe this may be just a matter of adding `/usr/local/cuda/bin` to the `PATH` for the "rapids" user, but I haven't confirmed.

**Comment by ajschmidt8** [comment]
@rlratzel, this should be fixed in our latest images since we removed the `rapids` user and switched back to using the `root` user.
