### ISSUE TITLE
[FEA] Add AzureML dependencies to docker images

### ISSUE THREAD

**Issue by jacobtomlinson** [rapidsai/docker#205]
**Is your feature request related to a problem? Please describe.**
Currently when using the RAPIDS docker images on AzureML there are errors due to `mpi4py` and `azureml-sdk` not being included which are requirements for AzureML.

**Describe the solution you'd like**
Add `mpi4py` via `conda` and `azureml-sdk` via `pip` (not currently on conda-forge) to the RAPIDS Docker images.

This adds ~650MB to the image size.

```
REPOSITORY                       TAG                                  IMAGE ID            CREATED             SIZE
rapidsai/rapidsai                cuda10.1-runtime-ubuntu16.04-py3.7   c870fd439a58        7 days ago          9.74GB
rapidsai/rapidsai                azureml-test                         f5261000ef69        13 seconds ago      10.4GB
```

**Describe alternatives you've considered**
Alternatively we could have an AzureML specific image which adds these libraries on top of the regular images. However this increases build complexity and number of Docker images.

**Comment by ajschmidt8** [comment]
@jacobtomlinson, is this something that could be solved with the env variables introduced in #170 (`EXTRA_CONDA_PACKAGES` & `EXTRA_PIP_PACKAGES`)? We currently omit PyTorch from our images due to its large size, so I'm not sure we'd want to add other large packages either. And also maintaining more variations isn't ideal either.

**Comment by jacobtomlinson** [comment]
Ah yes those env vars may be a solution! Let me try.

**Comment by jacobtomlinson** [comment]
It seems that AzureML overrides the default entrypoint with a custom one. So our preparation script is never called and we can't use the `EXTRA_` options. I'm trying to see if I can override this option and set it back to our prepare script, but the config to get this working is getting a little unwieldy.

**Comment by ajschmidt8** [comment]
@jacobtomlinson, are you aware of the [rapidsai/cloud-ml-examples](https://github.com/rapidsai/cloud-ml-examples) images? They are built on top of the RAPIDs images and have `azureml-sdk` baked in ([link](https://github.com/rapidsai/cloud-ml-examples/blob/main/common/docker/Dockerfile.training.unified#L70-L73)).

**Comment by jacobtomlinson** [comment]
Ah awesome. That may be a good way forward then. Thanks @ajschmidt8
