### ISSUE TITLE
[FEA] Add extra packages in docker entrypoint

### ISSUE THREAD

**Issue by jacobtomlinson** [rapidsai/docker#25]
I would like to use the rapids docker image more interchangeable with the [dask docker image](https://github.com/dask/dask-docker). 

**Describe the solution you'd like**
The dask image (along with others) implements an [entrypoint script](https://github.com/dask/dask-docker/blob/master/base/prepare.sh) which installs extra packages from environment variables (`EXTRA_APT_PACKAGES`, `EXTRA_CONDA_PACKAGES`, `EXTRA_PIP_PACKAGES`). This allows users to customize their containers without having to build their own.

**Describe alternatives you've considered**
The alternative to this is for people to build their own docker images backed on the rapids image and host it somewhere like Docker Hub. It would be good if users could get started with the docker image without prior knowledge of docker.

**Comment by ajschmidt8** [comment]
@jacobtomlinson, we're currently going through these older issues to see what still needs to be addressed. I just wanted to confirm whether or not this feature request is still valid. Please let me know.

**Comment by jacobtomlinson** [comment]
No problem, these things happen!

I think this would still be valuable for existing Dask users who are transitioning over to RAPIDS as they have come to expect this in the Dask images. It comes up from time to time.

**Comment by ajschmidt8** [comment]
@jacobtomlinson, addressed in #170. Feel free to review!
