### ISSUE TITLE
[QST] Docker image for use with SageMaker

### ISSUE THREAD

**Issue by arlenis65** [rapidsai/docker#253]
**What is your question?**
Hi. I'd like to use cuDF and maybe cuML with AWS SageMaker. For this, I need the smallest possible docker image to start with before installing other libraries.

I was thinking of using Python3.8-slim:buster but I'm thinking the container described here would be even better:
https://rapids.ai/start.html

I then ran into the documentation in Docker Hub that there is also a version of the container without the notebooks (`base` and `runtime`).

On top of this, I'm also confused between these tags:
rapidsai/rapidsai-core-nightly:cuda11.0-base-ubuntu20.04
rapidsai/rapidsai-core-nightly:cuda11.0-base-ubuntu20.04-py3.8

Can I get advice on which container I should be using? My specific requirements are as follows:
- either stable or nightly version: can I use nightly for dev work? Will it be buggy and will the future changes break functions between the stable and nightly version?
- RAPIDS Core w/o BlazingSQL
- Ubuntu 20.04, Python 3.8 is preferable
- CUDA 11.0

I will be using the p3 instances mostly.

Thanks.

**Comment by kkraus14** [comment]
Transferred issue to `docker` repo as it's more appropriate. You can see the image descriptions here: https://github.com/rapidsai/docker#image-types.

Using the `core` images definitely sounds like the correct route for you. I'm not sure the difference between those two tags, maybe someone else can chime in?

**Comment by ajschmidt8** [comment]
Hi @arlenis65. Keith is correct about the `core` images being right for you. Regarding these two tags:

- rapidsai/rapidsai-core-nightly:cuda11.0-base-ubuntu20.04
- rapidsai/rapidsai-core-nightly:cuda11.0-base-ubuntu20.04-py3.8

The first image uses our Dockerfile's default Python version, which is `3.7` ([src](https://github.com/rapidsai/docker/blob/branch-0.18/generated-dockerfiles/rapidsai-core_ubuntu18.04-base.Dockerfile#L10)). This image tag exists for users who don't care which Python version they're using. There is also a `rapidsai/rapidsai-core-nightly:cuda11.0-base-ubuntu20.04-py3.7` tag which explictly states the Python version for `3.7`. Other than the Python versions, these images are all identical. Use whichever tag suits your Python needs.

Regarding stable vs. nightly. We strive to ensure our nightly containers are as stable as possible, but we can't make any guarantees. If stability is crucial for you, then the `stable` images would make the most sense.

Hope that helps. Let me know if this answers your questions.
