### ISSUE TITLE
[BUG] cuhornet error on Docker build

### ISSUE THREAD

**Issue by pseudotensor** [rapidsai/docker#302]
in branch "branch-0.18"

```
docker build --build-arg CUDA_VER=11.0 --build-arg PYTHON_VER=3.7  -f generated-dockerfiles/rapidsai-core_centos7-devel.Dockerfile context
```

Goes for a while, then hits:

...
populating cuhornet                                                                                                                                                                                         
Scanning dependencies of target cuhornet-populate                                                                                                                                                           
[ 11%] Creating directories for 'cuhornet-populate'                                                                                                                                                         
[ 22%] Performing download step (git clone) for 'cuhornet-populate'                                                                                                                                         
Cloning into 'cuhornet-src'...                                                                                                                                                                              
fatal: reference is not a tree: 9cb8e8803852bd895a9c95c0fe778ad6eeefa7ad                                                                                                                                    
CMake Error at cuhornet-subbuild/cuhornet-populate-prefix/tmp/cuhornet-populate-gitclone.cmake:40 (message):                                                                                                
  Failed to checkout tag: '9cb8e8803852bd895a9c95c0fe778ad6eeefa7ad'                                                                                                                                        

gmake[2]: *** [cuhornet-populate-prefix/src/cuhornet-populate-stamp/cuhornet-populate-download] Error 1                                                                                                     
gmake[1]: *** [CMakeFiles/cuhornet-populate.dir/all] Error 2
gmake: *** [all] Error 2

CMake Error at /opt/conda/envs/rapids/share/cmake-3.18/Modules/FetchContent.cmake:987 (message):
  Build step for cuhornet failed: 2
Call Stack (most recent call first):
  /opt/conda/envs/rapids/share/cmake-3.18/Modules/FetchContent.cmake:1082:EVAL:2 (__FetchContent_directPopulate)
  /opt/conda/envs/rapids/share/cmake-3.18/Modules/FetchContent.cmake:1082 (cmake_language)
  CMakeLists.txt:283 (FetchContent_Populate)

-- Configuring incomplete, errors occurred!
See also "/rapids/cugraph/cpp/build/CMakeFiles/CMakeOutput.log".
See also "/rapids/cugraph/cpp/build/CMakeFiles/CMakeError.log".
The command '/bin/bash -c cd ${RAPIDS_DIR}/cugraph &&   source activate rapids &&   ccache -s &&   ./build.sh --allgpuarch cugraph libcugraph' returned a non-zero code: 1
```

**Comment by afender** [comment]
Thanks for catching that. Trying to disable GIT_SHALLOW there: https://github.com/rapidsai/cugraph/pull/1535

**Comment by raydouglass** [comment]
The cugraph PR is merged, so this issue should be resolved. Feel free to reopen if necessary. Thanks again for reporting the issue @pseudotensor!
