### ISSUE TITLE
[QST] cuda 11.2 for rapids

### ISSUE THREAD

**Issue by pseudotensor** [rapidsai/docker#304]
I'm confused what the release schedule is like for rapids.  It seems only cuda 11.0 is available as docker for build, final image, and conda files.

However, there is a cuda toolkit==11.1 and 11.2, but no rapids matching.

Feature request would be to push to conda the other patched revision versions of latest cuda toolkit version at least, e.g. 11.2 for now.

Also, you can see that torch 1.8.1 says to use cuda toolkit 11.1 not 11.0, so there would be no way to install rapids + pytorch with existing recommendations, even from docker images.

https://pytorch.org/get-started/locally/

Even more specifically, the latest actual image is 11.2.2.

**Comment by ajschmidt8** [comment]
Hi @pseudotensor,

To answer your questions:

We currently post our release schedule on our website here: https://docs.rapids.ai/maintainers

CUDA 11.2 support will be released in RAPIDS v0.19. Our current `0.19` [nightly images](https://hub.docker.com/r/rapidsai/rapidsai-nightly/tags?page=1&ordering=last_updated&name=0.19-cuda11.2) and [nightly conda packages](https://anaconda.org/rapidsai-nightly/rapids/files) have support for CUDA 11.2.

While we don't test for compatibility with PyTorch, our CUDA 11.2 images should work with PyTorch if they also have 11.2 packages available.

Hope this helps. Let me know if you have any additional questions.

**Comment by pseudotensor** [comment]
Thanks, that's great.  Thanks for pointing to the release schedule.  I don't see there or elsewhere the fact that cuda 11.2 will be supported for rapids 0.19, but I guess one can gather it from the nightly images/packages.  Thanks!

**Comment by pseudotensor** [comment]
Slight follow-up.  I tried:
```
conda install -c rapidsai -c rapidsai-nightly -c nvidia -c conda-forge -c anaconda -c defaults python=3.8 nomkl cudatoolkit=11.2.2 rapids-blazing=0.19 cudf=0.19 cuml=0.19 cugraph=0.19 cusignal=0.19 custreamz=0.19 pyarrow cython matplotlib scikit-learn pynvml pandas numpy fastavro fsspec dask-cuda dask-xgboost xgboost dask distributed networkx scipy
```
and this does not work due to conflicts.  So I guess nightly 0.19 support is only for cuda toolkit 11.2 and not 11.2.2?

**Comment by ajschmidt8** [comment]
@pseudotensor, Do you need `11.2.2` exactly? After using the command below to create a minimal `rapids` environment, conda installs `cudatoolkit-11.2.72`. Changing the command below to use `cudatoolkit=11.2.2` instead of `cudatoolkit=11.2` did fail for me locally though.

```sh
conda create -n rapids-0.19 -c rapidsai-nightly -c nvidia -c conda-forge \
    -c defaults rapids-blazing=0.19 python=3.8 cudatoolkit=11.2
```

I can't speak to the compatibility of the all 3rd party libraries you have listed in your command. I would recommend installing the minimal RAPIDS environment first and incrementally adding other packages to see if they're compatible with the conda environment.

**Comment by pseudotensor** [comment]
Yes, I guess it's not clear what is 11.2.2. vs. 11.2.72 etc.

I'm particularly interested in this issue because if I install docker with some cuda as base image, then also use conda to install condatoolkit, then I have a duplicate install of cuda and it takes alot of extra space.  One might imagine de-dupping the install, but that is only possible if the versions match exactly.

Or do you have some recommendation in this regard?

**Comment by kkraus14** [comment]
@pseudotensor this is a bug on our end with regards to `cudatoolkit` versioning. We were originally following the versioning of the cuda runtime which is 11.2.72 but then moved to align to conda-forge which is just using release versioning of 11.2.2. Now it looks like we're getting builds against 11.2.72 which then causes a constraint of `>=11.2.72,<11.3.0a0`.

We'll dig in and resolve this. Thanks for reporting!

**Comment by pseudotensor** [comment]
Also see this from same conda setup when doing any pip install of anything.
```
ERROR: dask-cudf 0.19.0a0+362.g8e1ffd4e56 requires cupy-cuda110, which is not installed.
ERROR: cudf 0.19.0a0+362.g8e1ffd4e56 requires cupy-cuda112, which is not installed.
```
I can install cupy-cuda112, but why does dask-cudf and cudf require different cuda110 vs. cuda112 for rapids 0.19?

**Comment by pseudotensor** [comment]
@kkraus14 

A related problem is that tensorflow 2 has "bug" that repeats ptxas check many times, leading to crazy slow use with cuda and conda.  A solution in conda is to install the cudatoolkit-dev that includes ptxas.  However, the cudatoolkit and cudatoolkit-dev are out of sync.

So one ends up with 11.2 and 11.0 cuda.

These kind of sync issues between rapids, cuda, docker images, etc. would really help in using rapids.  Alternatively, ptxas could be in cudatoolkit and not just -dev.

https://github.com/tensorflow/tensorflow/issues/40036

**Comment by kkraus14** [comment]
This is not an issue the RAPIDS team can solve and RAPIDS is not dependent on `ptxas`. `ptxas` is not redistributable per the CUDA EULA and I don't believe is included in the cuda runtime docker images.

You could probably create a new base image from the cuda dev images and pay the size cost of having duplicate cuda toolkit libraries installed (system and conda) which would likely solve the problem for you.

We're working on making non-conda install paths easier for RAPIDS libraries, but unfortunately we don't have the power to change NVIDIA licensing issues.

**Comment by pseudotensor** [comment]
> This is not an issue the RAPIDS team can solve and RAPIDS is not dependent on `ptxas`. `ptxas` is not redistributable per the CUDA EULA and I don't believe is included in the cuda runtime docker images.
> 
> You could probably create a new base image from the cuda dev images and pay the size cost of having duplicate cuda toolkit libraries installed (system and conda) which would likely solve the problem for you.
> 
> We're working on making non-conda install paths easier for RAPIDS libraries, but unfortunately we don't have the power to change NVIDIA licensing issues.

Yes, I understand.  I was giving context for a problem that does exist in general, which is all the various conda packages available are not entirely consistent.  cudatoolkit and cudatoolkit-dev do not have matching versions.

This does affect RAPIDS use since one will try (of course) to install rapids + tensorflow.  One cannot only think of how RAPIDS is built, but how it's used.

**Comment by kkraus14** [comment]
> Yes, I understand. I was giving context for a problem that does exist in general, which is all the various conda packages available are not entirely consistent. cudatoolkit and cudatoolkit-dev do not have matching versions.

`cudatoolkit-dev` is not a package that we're involved in and generally isn't something that's supported by NVIDIA in any way.

> This does affect RAPIDS use since one will try (of course) to install rapids + tensorflow. One cannot only think of how RAPIDS is built, but how it's used.

Yes I'm very aware, but we unfortunately can't control the entire ecosystem. We don't control the CUDA EULA and what can or can't be redistributed. I've escalated internally and am trying to push things in the right direction. We're working on improving the ability to build / install RAPIDS libraries as easily as possible to allow integrating it into non-conda environments and containers and whatnot, but we're not quite there yet.

> Also see this from same conda setup when doing any pip install of anything.
> 
> ```
> ERROR: dask-cudf 0.19.0a0+362.g8e1ffd4e56 requires cupy-cuda110, which is not installed.
> ERROR: cudf 0.19.0a0+362.g8e1ffd4e56 requires cupy-cuda112, which is not installed.
> ```
> 
> I can install cupy-cuda112, but why does dask-cudf and cudf require different cuda110 vs. cuda112 for rapids 0.19?

Thanks for reporting this, this is a bug in our `dask-cudf` conda packages that we'll resolve.

**Comment by rg2009** [comment]
error running rapidsai on AWS Deep Learning AMI

ubuntu@ip-10-119-22-175:~$ sudo docker run --gpus all --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786 rapidsai/rapidsai:cuda10.2-runtime-ubuntu18.04
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: nvml error: driver not loaded: unknown.

any suggestions on how to resolve this appreciated

**Comment by alborotogarcia** [comment]
FYI @kkraus14 @pseudotensor just tested that tensorflow-gpu 2.5.0 works fine with rapidsai by installing from esri's channel
` conda install -c esri tensorflow-gpu `
though this also installs cudnn 8.1 in docker image.
