### ISSUE TITLE
[BUG] return error codes aren't checked when the extra package installation fails

### ISSUE THREAD

**Issue by sriramch** [rapidsai/docker#361]
**Describe the bug**
presently, when we use the RAPIDS nightly image, we specify extra APT/PIP packages etc. to install [thusly](https://github.com/rapidsai/docker/blob/branch-21.10/context/packages.sh#L11). however, when those packages can't be installed for whatever reason, that error code isn't propagate back to the [caller](https://github.com/rapidsai/docker/blob/branch-21.10/context/entrypoint.sh#L14)

the error codes are absorbed and ignored, and the return value if the `entrypoint` script is the return value from [this](https://github.com/rapidsai/docker/blob/branch-21.10/context/entrypoint.sh#L31) command.

**Steps/Code to reproduce bug**
   - `entrypoint` invoked like: `DASK_DISTRIBUTED__DASHBOARD__PROMETHEUS__NAMESPACE=ngcjob_appmetrics_dask EXTRA_PIP_PACKAGES=foo /opt/docker/bin/entrypoint --unquote-exec dask-scheduler --dashboard-address :8787 --port 8786 --protocol ws` 

**Expected behavior**
bail out early when the packages couldn't be installed (or provide an option to the user to customize this behavior).

**Environment details (please complete the following information):**
 - Environment location: Docker
 - Method of cuDF install: Docker
   - `docker pull rapidsai/rapidsai-core:21.08-cuda11.0-runtime-ubuntu18.04-py3.7`

**Additional context**
we are invoking this in the NGC context when we create NGC jobs, and want the job creation fail if *any* of the extra packages the user wants couldn't be installed, as the user expects them to be present to successfully run their experiments.

FYI: @jacobtomlinson

**Comment by jacobtomlinson** [comment]
Thanks @sriramch.

It looks like the entrypoint script will continue regardless of any failures in any commands. Perhaps we want to add `set -e` on it?

**Comment by ajschmidt8** [comment]
@sriramch, @jacobtomlinson thanks for bringing this to our attention. Like Jacob mentioned, it seems that a `set -e` will fix this. I'll try to knock this out this week when I have some time.

**Comment by sriramch** [comment]
thanks @ajschmidt8. a reason why `set -e` isn't preferable is documented [here](http://mywiki.wooledge.org/BashFAQ/105)

**Comment by jacobtomlinson** [comment]
I agree that `set -e ` isn't perfect but I think it's an improvement on what we have now (nothing).
