### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by rshankk** [rapidsai/docker#369]
**Describe the bug**

The RAPIDS entry point script triggers start_jupyter.sh to bring up the jupyer notebook. When we run the dask scheduler and worker on different nodes using the RAPIDS image, it triggers start of jupyter notebook on the worker nodes too which is unnecessary. EntryPoint script should provide a config option to not to trigger start_jupyter.sh so that jupyter notebook can be brought only on dask scheduler node. 

**Steps/Code to reproduce bug**

Use RAPIDS entrypoint script on dask scheduler and dask worker nodes.

**Expected behavior**

Jupyter notebook should be brought up only on dask scheduler node. 

**Environment details (please complete the following information):**

 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
    docker 
    
 - Method of cuDF install: [conda, Docker, or from source]
    docker pull rapidsai/rapidsai-core:21.08-cuda11.0-runtime-ubuntu18.04-py3.7

 - Please run and attach the output of the `cudf/print_env.sh` script to gather relevant environment details
 

**Additional context**

**Comment by ajschmidt8** [comment]
@rshankk, there is an environment variable, `DISABLE_JUPYTER`, that can be set at runtime to disable JupyterLab from starting automatically with the container. For instance, you should be able to do run the following code to prevent JupyterLab from running at start up:

```sh
docker run -e DISABLE_JUPYTER=true ...
```

This functionality is documented on our DockerHub README [here](https://hub.docker.com/r/rapidsai/rapidsai). Please let me know if this works for you so we can close this issue.

**Comment by ajschmidt8** [comment]
Closing issue.
