### ISSUE TITLE
CUDA : N/A on docker container 

### ISSUE THREAD

**Issue by rahulgupta271** [rapidsai/docker#405]
While using below Release

rapidsai/rapidsai:21.10-cuda11.0-runtime-centos7-py3.7 we are seeing **CUDA Version: N/A** . seems issues ith CUDA toolkit. 

Also i am not seeing the cuda lib initilizing while launching a container:

sh-4.2# nvidia-smi
Thu Dec  9 15:21:09 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.36.06    Driver Version: 450.36.06    **CUDA Version: N/A**      |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:00:1B.0 Off |                    0 |
| N/A   37C    P0    37W / 300W |      3MiB / 16160MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

sh-4.2# cd /usr/lib
sh-4.2# ls -lrt
total 8
dr-xr-xr-x. 2 root root    6 Apr 11  2018 sse2
dr-xr-xr-x. 2 root root    6 Apr 11  2018 games
drwxr-xr-x. 3 root root   64 Apr 11  2018 debug
drwxr-xr-x. 3 root root   33 Sep 30  2020 gcc
drwxr-xr-x. 2 root root    6 Oct  1  2020 modules-load.d
drwxr-xr-x. 2 root root    6 Oct  1  2020 binfmt.d
drwxr-xr-x. 3 root root   27 Nov 13  2020 python2.7
drwxr-xr-x. 1 root root   23 Nov 13  2020 dracut
drwxr-xr-x. 2 root root  124 Nov 13  2020 yum-plugins
drwxr-xr-x. 2 root root    6 Nov 13  2020 modules
-rw-r--r--. 1 root root  393 Nov 23  2020 os-release
drwxr-xr-x. 1 root root   23 Feb  2  2021 kernel
drwxr-xr-x. 1 root root   55 Oct 18 09:13 locale
drwxr-xr-x. 1 root root 4096 Oct 18 09:13 rpm
lrwxrwxrwx. 1 root root   10 Oct 18 13:34 cpp -> ../bin/cpp
drwxr-xr-x. 1 root root   78 Oct 18 13:34 udev
drwxr-xr-x. 1 root root   30 Oct 18 13:34 tmpfiles.d
drwxr-xr-x. 1 root root  177 Oct 18 13:34 systemd
drwxr-xr-x. 1 root root   28 Oct 18 13:34 sysctl.d
drwxr-xr-x. 1 root root   53 Oct 18 13:34 modprobe.d
sh-4.2# 

Can anyone please look into it and share the thoughts,

**Comment by ajschmidt8** [comment]
Hi @rahulgupta271. Can you provide the commands that you're using to start the container?

**Comment by rahulgupta271** [comment]
Thanks for your response.

/usr/bin/docker run -dit --gpus '"device=0"' --memory="56g" --cpus="6"  --runtime=nvidia  --name rapid-device-gpu --expose=8888 -v /home/aa01/air9-ocp/users-home/gpu/nromane:/tf/files -p 10065:8888 -p 10067:8787 -p 10068:8786 -p 10066:6006 ab8c28f61ccc

**Comment by ajschmidt8** [comment]
Thanks for this information. I'm unable to replicate the problem on my end. I suspect there could be an issue with your host machine setup. Can you provide the following?

1) The output of `nvidia-smi` on the host machine (i.e. not in the container)
2) The output of `nvidia-docker version` on the host machine
3) The output of `docker run --rm -it --runtime=nvidia rapidsai/rapidsai:21.10-cuda11.0-runtime-centos7-py3.7 nvidia-smi`

**Comment by ajschmidt8** [comment]
@rahulgupta271, apologies for the late reply here. As indicated on our website below, the minimum supported CUDA driver for RAPIDS is `450.80.02`. It seems that your host machine has driver `450.36.06`, which is older than our minimum supported version. Can you upgrade the driver version on your host machine and try again?

https://rapids.ai/start.html

**Comment by ajschmidt8** [comment]
Closing issues
