### ISSUE TITLE
[BUG] Docker hub images aren't present

### ISSUE THREAD

**Issue by singlecheeze** [rapidsai/docker#416]
Docker hub images aren't present for nightly 22.02 for most images, and the ones there don't have complete image set for older CUDA than 11.5
![Screenshot from 2021-12-16 13-14-17](https://user-images.githubusercontent.com/12156213/146426838-ba9cac08-4da9-42b0-a65d-a55c452dc008.png)
![Screenshot from 2021-12-16 13-13-12](https://user-images.githubusercontent.com/12156213/146426839-d0b6382e-6ca2-47ca-b2c3-a80c30917a87.png)
.

**Comment by ajschmidt8** [comment]
Thanks for bringing this to our attention. The `22.02` images are currently experiencing some builds issues that we will be working to address in the coming days.

**Comment by ajschmidt8** [comment]
The `22.02` images are currently released. Closing this issue.
