### ISSUE TITLE
[FEA] Install RAPIDS libraries in the default conda environment

### ISSUE THREAD

**Issue by daxiongshu** [rapidsai/docker#439]
**Is your feature request related to a problem? Please describe.**
Currently, RAPIDS libraries are installed in the `rapids` conda environment instead of the default conda environment `base` in the rapids docker image `rapidsai/rapidsai-core:22.02-cuda11.5-base-ubuntu20.04-py3.8`. This creates a problem when the default environment `base` is forced to be used or there is no way to activate `rapids` environment when using the docker image. A real use case is [viash](https://github.com/openproblems-bio/neurips2021_multimodal_topmethods/issues/19)

**Describe the solution you'd like**
RAPIDS libraries are installed in the default `base` conda environment. For example, `PyTorch` is installed in the `base` environment in PyTorch docker image, `pytorch/pytorch:1.9.0-cuda11.1-cudnn8-runtime`

**Comment by daxiongshu** [comment]
A related issue might be issue #438

**Comment by ajschmidt8** [comment]
@daxiongshu, thanks for bringing this to our attention. We are currently exploring removing the `rapids` conda environment and using the default `base` conda environment instead. This will require a lot of changes to our images and the associated CI, so there is no ETA at this moment.

**Comment by raydouglass** [comment]
This will be resolved as part of the overhaul: #539 & #545
