### ISSUE TITLE
[BUG] Nightly Container start failed with extra conda package

### ISSUE THREAD

**Issue by PingHao** [rapidsai/docker#472]
**Describe the bug**
With latest nightly image _rapidsai/rapidsai-core-nightly:22.06-cuda11.0-runtime-ubuntu18.04-py3.8_, id 503c9ffc2d9f, start container with EXTRA_CONDA_PACKAGES set would failed. 

Stable image don't have this issue, tested with _rapidsai/rapidsai-core:22.04-cuda11.0-runtime-ubuntu18.04-py3.8_

**Steps/Code to reproduce bug**
```
$ docker run --rm -e EXTRA_CONDA_PACKAGES="pytz" rapidsai/rapidsai-core-nightly:22.06-cuda11.0-runtime-ubuntu18.04-py3.8
This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.download.nvidia.com/licenses/NVIDIA_Deep_Learning_Container_License.pdf

EXTRA_CONDA_PACKAGES environment variable found. Installing packages.
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working...      failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working...
```
**Expected behavior**
no error with _EXTRA_CONDA_PACKAGES_ set

**Comment by ajschmidt8** [comment]
@PingHao, we can't make any guarantees about the compatibility of 3rd-party packages with our containers. It's possible that the existing dependencies within the container have changed between the last stable release and the current nightly release. This could be contributing to the issue with conda not correctly solving the environment.

Unfortunately there's nothing more we can do here, so I will close this issue.
