### ISSUE TITLE
[BUG] pytables dependency not available in RAPIDS container

### ISSUE THREAD

**Issue by miguelusque** [rapidsai/docker#48]
**Describe the bug**
When trying to export to HDF5 file format, the following error is displayed:

```
/opt/conda/envs/rapids/lib/python3.6/site-packages/cudf/io/hdf.py:26: UserWarning: Using CPU via Pandas to write HDF dataset, this may be GPU accelerated in the future
  "Using CPU via Pandas to write HDF dataset, this may "
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/opt/conda/envs/rapids/lib/python3.6/site-packages/pandas/io/pytables.py in __init__(self, path, mode, complevel, complib, fletcher32, **kwargs)
    465         try:
--> 466             import tables  # noqa
    467         except ImportError as ex:  # pragma: no cover

ModuleNotFoundError: No module named 'tables'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-4cfff73d1cdf> in <module>
      6 df.head()
      7 
----> 8 df.to_hdf("hello.hdf5", key="tmp")

/opt/conda/envs/rapids/lib/python3.6/site-packages/cudf/core/dataframe.py in to_hdf(self, path_or_buf, key, *args, **kwargs)
   3781         import cudf.io.hdf as hdf
   3782 
-> 3783         hdf.to_hdf(path_or_buf, key, self, *args, **kwargs)
   3784 
   3785     @ioutils.doc_to_dlpack()

/opt/conda/envs/rapids/lib/python3.6/site-packages/cudf/io/hdf.py in to_hdf(path_or_buf, key, value, *args, **kwargs)
     28     )
     29     pd_value = value.to_pandas()
---> 30     pd.io.pytables.to_hdf(path_or_buf, key, pd_value, *args, **kwargs)

/opt/conda/envs/rapids/lib/python3.6/site-packages/pandas/io/pytables.py in to_hdf(path_or_buf, key, value, mode, complevel, complib, append, **kwargs)
    271     if isinstance(path_or_buf, string_types):
    272         with HDFStore(path_or_buf, mode=mode, complevel=complevel,
--> 273                       complib=complib) as store:
    274             f(store)
    275     else:

/opt/conda/envs/rapids/lib/python3.6/site-packages/pandas/io/pytables.py in __init__(self, path, mode, complevel, complib, fletcher32, **kwargs)
    467         except ImportError as ex:  # pragma: no cover
    468             raise ImportError('HDFStore requires PyTables, "{ex!s}" problem '
--> 469                               'importing'.format(ex=ex))
    470 
    471         if complib is not None and complib not in tables.filters.all_complibs:

ImportError: HDFStore requires PyTables, "No module named 'tables'" problem importing
```

**Steps/Code to reproduce bug**
```
$ docker pull rapidsai/rapidsai:cuda10.0-runtime-ubuntu18.04 
$ docker run --runtime=nvidia --rm -it -v /raid/miguelm:/rapids/notebooks/miguelm  -p 8888:8888 -p 8787:8787 -p 8786:8786 rapidsai/rapidsai:cuda10.0-runtime-ubuntu18.04 

```

Create a notebook with the following code:

```
import cudf

df = cudf.DataFrame([('a', list(range(20))),
                     ('b', list(reversed(range(20)))),
                     ('c', list(range(20)))])
df.head()

df.to_hdf("hello.hdf5", key="tmp")
```

**Expected behaviour**
The example DataFrame should be stored in an HDF5 file.

I think the issue is due that the container does not include pytables dependency.

Hope it helps!

**Comment by kkraus14** [comment]
I'm -1 on including this in the container. HDF5 isn't the most common format for DataFrames and if a user wants to work with them they can easily run a `conda install pytables` in order to get it.

**Comment by miguelusque** [comment]
Hi @kkraus14 ,

My understanding of a container is that it is an isolated piece of software that runs as is, without any modification. 

The user should do the dependency install, save a new version of the container, store it in a container repository...

Also, why this third party dependency cannot be in the container, while many others are?

Just trying to understand.

Regards,
Miguel

**Comment by msadang** [comment]
@miguelusque Did you still want to include the pytables dependancy?

**Comment by miguelusque** [comment]
Hi @msadang ,

I’d say the question is if we should have included in RAPIDS containers the dependencies needed in order to be able use 100% of RAPIDS functionality out of the box.

This is not related to any customer/personal project, but something I noticed while performing some tests, and I thought it would be good to comment to you.

Hope it helps!

Regards,
Miguel

**Comment by ajschmidt8** [comment]
@miguelusque, we recently merged #170, which enables `conda`, `pip`, `apt`, and `yum` packages to be installed via environment variables provided to the `docker run` command. Documentation can be found [here on DockerHub](https://hub.docker.com/r/rapidsai/rapidsai-nightly) under the `Usage` section.

I don't think we have plans to add `pytables` to the containers, but this should provide a convenient workaround. Closing this issue, but feel free to post back here if you have any issues with the new feature.

**Comment by miguelusque** [comment]
Hi @ajschmidt8 , 

Sure! It works for me. Thanks!

Just a quick doubt: Does the `EXTRA_CONDA_PACKAGES` allows adding packages from different conda channels? 

Thanks!

Regards,
Miguel

**Comment by ajschmidt8** [comment]
@miguelusque, I will test different conda channels and let you know.

**Comment by ajschmidt8** [comment]
it looks like custom channels do work. your `docker run` command would look something like this, where `-c <channel>` is the custom channel:
`docker run ... -e EXTRA_CONDA_PACKAGES="-c ajschmidt rapids-pytest-benchmark" ...`

**Comment by miguelusque** [comment]
That is outstanding. Thank you for double checking it!
