### ISSUE TITLE
[BUG] rapidsai/rapidsai-core:23.02-cuda11.5-runtime-ubuntu22.04-py3.8 not on github

### ISSUE THREAD

**Issue by ntabris** [rapidsai/docker#533]
The release selector on https://rapids.ai/start.html says you can use `rapidsai/rapidsai-core:23.02-cuda11.5-runtime-ubuntu22.04-py3.8`.

<img width="1250" alt="image" src="https://user-images.githubusercontent.com/46289310/219511342-5d1c1816-7822-4d09-87c1-f997d81dfb61.png">

This doesn't appear to be on Docker Hub. There is a corresponding ubuntu20.04 image, though.

**Comment by ajschmidt8** [comment]
@ntabris, thanks for bringing this to our attention.

Ubuntu 22.04 is only supported for CUDA 11.8, which is why the image is missing.

We'll update the selector accordingly.
