### ISSUE TITLE
No nvcc or nvidia-smi in docker

### ISSUE THREAD

**Issue by sharthZ23** [rapidsai/docker#534]
**Describe the bug**
Hi, im using _rapidsai/rapidsai:cuda11.8-runtime-ubuntu20.04-py3.8_ from https://hub.docker.com/r/rapidsai/rapidsai/ (ebe946ff95b5ac9671062134eed604844790837e6805db9d951c7311b614f7d9) on Windows 10 with Docker Desktop and i have several problems with it.
- I cant run anything related with GPU. When i use terminal in Docker, i cant access nvcc or nvidia-smi (`/bin/sh: 12: nvcc: not found`).
- Also dask apps doesnt start up (on ports 8787 and 8786). 
- Jupyter works, but if i try run any notebook i get `ImportError: libcuda.so.1: cannot open shared object file: No such file or directory`.

It looks like i have problems with CUDA inside Docker container, but i dont know why.

**Steps/Code to reproduce bug**
- Download image with tag, which match CUDA version on my PC in Docket desktop
- Run container with mapping ports only (8888, 8787, 8786)

**Expected behavior**
- Running any notebook without errors

**Environment details (please complete the following information):**
 - Environment location: Docker
 - Method of cuDF install: Docker
   - `docker pull rapidsai/rapidsai:cuda11.8-runtime-ubuntu20.04-py3.8` (ebe946ff95b5ac9671062134eed604844790837e6805db9d951c7311b614f7d9)
   - docker run 
```
docker run 
        --hostname=87889cfde62d 
	--mac-address=02:42:ac:11:00:02 
	--env=PATH=/opt/conda/condabin:/opt/conda/envs/rapids/bin:/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin 
        --env=NVARCH=x86_64 
	--env=NVIDIA_REQUIRE_CUDA=cuda>=11.8 brand=tesla,driver>=450,driver<451 brand=tesla,driver>=470,driver<471 brand=unknown,driver>=470,driver<471 brand=nvidia,driver>=470,driver<471 brand=nvidiartx,driver>=470,driver<471 brand=geforce,driver>=470,driver<471 brand=geforcertx,driver>=470,driver<471 brand=quadro,driver>=470,driver<471 brand=quadrortx,driver>=470,driver<471 brand=titan,driver>=470,driver<471 brand=titanrtx,driver>=470,driver<471 brand=tesla,driver>=510,driver<511 brand=unknown,driver>=510,driver<511 brand=nvidia,driver>=510,driver<511 brand=nvidiartx,driver>=510,driver<511 brand=geforce,driver>=510,driver<511 brand=geforcertx,driver>=510,driver<511 brand=quadro,driver>=510,driver<511 brand=quadrortx,driver>=510,driver<511 brand=titan,driver>=510,driver<511 brand=titanrtx,driver>=510,driver<511 brand=tesla,driver>=515,driver<516 brand=unknown,driver>=515,driver<516 brand=nvidia,driver>=515,driver<516 brand=nvidiartx,driver>=515,driver<516 brand=geforce,driver>=515,driver<516 brand=geforcertx,driver>=515,driver<516 brand=quadro,driver>=515,driver<516 brand=quadrortx,driver>=515,driver<516 brand=titan,driver>=515,driver<516 brand=titanrtx,driver>=515,driver<516 
	--env=NV_CUDA_CUDART_VERSION=11.8.89-1 
	--env=NV_CUDA_COMPAT_PACKAGE=cuda-compat-11-8 
	--env=CUDA_VERSION=11.8.0 
	--env=LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64 --env=NVIDIA_VISIBLE_DEVICES=all 
	--env=NVIDIA_DRIVER_CAPABILITIES=compute,utility 
	--env=NV_CUDA_LIB_VERSION=11.8.0-1 
	--env=NV_NVTX_VERSION=11.8.86-1 
	--env=NV_LIBNPP_VERSION=11.8.0.86-1 
	--env=NV_LIBNPP_PACKAGE=libnpp-11-8=11.8.0.86-1 
	--env=NV_LIBCUSPARSE_VERSION=11.7.5.86-1 
	--env=NV_LIBCUBLAS_PACKAGE_NAME=libcublas-11-8 
	--env=NV_LIBCUBLAS_VERSION=11.11.3.6-1 
	--env=NV_LIBCUBLAS_PACKAGE=libcublas-11-8=11.11.3.6-1 
	--env=NV_LIBNCCL_PACKAGE_NAME=libnccl2 
	--env=NV_LIBNCCL_PACKAGE_VERSION=2.16.2-1 
	--env=NCCL_VERSION=2.16.2-1 
	--env=NV_LIBNCCL_PACKAGE=libnccl2=2.16.2-1+cuda11.8 
	--env=NVIDIA_PRODUCT_NAME=CUDA 
	--env=DEBIAN_FRONTEND=noninteractive 
	--env=RAPIDS_VER=23.02 
	--env=RAPIDS_DIR=/rapids 
	--env=DASK_LABEXTENSION__FACTORY__MODULE=dask_cuda --env=DASK_LABEXTENSION__FACTORY__CLASS=LocalCUDACluster 
	--workdir=/rapids/notebooks 
	-p 8786:8786 -p 8787:8787 -p 8888:8888 
	--label='maintainer=NVIDIA CORPORATION <cudatools@nvidia.com>' 
	--label='org.opencontainers.image.ref.name=ubuntu' 
	--label='org.opencontainers.image.version=20.04' 
	--runtime=runc 
	-d rapidsai/rapidsai:cuda11.8-runtime-ubuntu20.04-py3.8
```

 - Please run and attach the output of the `cudf/print_env.sh` script to gather relevant environment details
   - My image doesnt have such file

**Additional context**
My PC specs:
- Windows 10
- 2x NVIDIA GeForce RTX 2080 TI
- Nvidia driver version: 531.18
- NVCC (output `nvcc.exe --version`):
  - Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
  - Cuda compilation tools, release 11.8, V11.8.89
  - Build cuda_11.8.r11.8/compiler.31833905_0

**Comment by ajschmidt8** [comment]
@sharthZ23, please let me know if my comment above has resolved your issue.

**Comment by ajschmidt8** [comment]
Closing this issue since I haven't heard back from the author.
