### ISSUE TITLE
password for jupyterlab daskscheduler and diagserver

### ISSUE THREAD

**Issue by ggmartins** [rapidsai/docker#537]
sorry if this is a dumb question, but
based on https://hub.docker.com/r/rapidsai/rapidsai/
how can I secure all of these ports with password?
 ```
$ docker pull rapidsai/rapidsai:23.02-cuda11.8-runtime-ubuntu22.04-py3.10
$ docker run --gpus all --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786 \
         rapidsai/rapidsai:23.02-cuda11.8-runtime-ubuntu22.04-py3.10
```

**Comment by ML-BCB** [comment]
Was wondering the same.

Did you ever get an answer / solve the above @ggmartins ?

**Comment by ggmartins** [comment]
@ML-BCB No, never :-(

**Comment by ML-BCB** [comment]
@ggmartins Thanks, will update here if / when I've figured it out :)

**Comment by ML-BCB** [comment]
Hey @ggmartins, managed to get this to work, if you append ` jupyter-lab --allow-root  --ip='0.0.0.0''

Then you should be able to use the token or set a password.

**Comment by ggmartins** [comment]
Fantastic, thanks a lot for this!
