### ISSUE TITLE
[FEA] Github self-hosted runner image

### ISSUE THREAD

**Issue by SoulEater45** [rapidsai/docker#547]
**Is your feature request related to a problem? Please describe.**
Currently there are not many viable options for self hosted runners, which run in a container and expose a GPU with CUDA support baked in. [iterativeai/cml](https://github.com/iterative/cml) has a viable option for this, but it is complicated to setup, and uses an access token to communicate with the runner setup, instead of using a provided runner roken.

**Describe the solution you'd like**
Create an additional image type derived from `base`, for example called `runner`, where the github runner environment is setup, and launces the config and run commands to bind the runner to a repository.

**Describe alternatives you've considered**
[iterativeai/cml](https://github.com/iterative/cml) is a possible alternative, but having rapidsai both as an execution image in a dask cluster and for testing has more consistency.

**Additional context**
Example setup for a self hosted runner given by Github:
```shell
## Download
# Create a folder
mkdir actions-runner && cd actions-runner
# Download the latest runner package
curl -o actions-runner-linux-x64-2.304.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.304.0/actions-runner-linux-x64-2.304.0.tar.gz
# Optional: Validate the hash
echo "292e8770bdeafca135c2c06cd5426f9dda49a775568f45fcc25cc2b576afc12f  actions-runner-linux-x64-2.304.0.tar.gz" | shasum -a 256 -c
# Extract the installer
tar xzf ./actions-runner-linux-x64-2.304.0.tar.gz

## Configure
# Create the runner and start the configuration experience
$ ./config.sh --url $REPO_URL_FROM_ENV --token $TOKEN_FROM_ENV
# Last step, run it!
$ ./run.sh
```

**Comment by ajschmidt8** [comment]
@SoulEater45, thanks for opening this issue.

Unfortunately this is not a use case that we plan on officially supporting.

However, you are free to create new images that use ours as the base.

I will close this issue.
