### ISSUE TITLE
Switch to non-`root` user

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/docker#564]
One improvement to the Docker images we might consider is switching to a non-`root` user and provide ownership of some files (like the Conda install) to that user.

This ideally means changing the user ID at container startup to match the user ID outside the image. However changing the user ID recursively at startup can get kind of slow.

A trick we use in conda-forge's Docker images is to [add a new group during build and change ownership of files to that group]( https://github.com/conda-forge/docker-images/blob/6d30f8fc76d5542a15330112f5b705bcc78b1887/scripts/run_commands#L67-L70 ). While this is still slow, this happens at Docker image build time (as opposed to container startup time). So the user need not wait for this. That way at container startup, we need only [add a user to the group owning those files]( https://github.com/conda-forge/docker-images/blob/7147486703592f7bed0e85d89c051ac26cf5aa5e/scripts/entrypoint#L8-L9 ) with [the user ID provided]( https://github.com/conda-forge/docker-images/blob/6d30f8fc76d5542a15330112f5b705bcc78b1887/.circleci/run_docker_build.sh#L36 ), which is much faster.

More details in [this blogpost]( https://denibertovic.com/posts/handling-permissions-with-docker-volumes/ )

Maybe we could adapt this strategy to our use case?

**Comment by raydouglass** [comment]
With the overhaul in #539, the images now use a non-root user of `rapids` who is a member of the `conda` group with write permissions to the conda directories.

Are there any other changes you need are needed?

**Comment by jakirkham** [comment]
Thanks Ray! 🙏

No let's close. We can follow up on anything else in new issues
