### ISSUE TITLE
Notebook image no longer works with Kubeflow?

### ISSUE THREAD

**Issue by MartinKlefas** [rapidsai/docker#587]
I was using the image at rapidsai/rapidsai:cuda11.8-runtime-ubuntu22.04-py3.10 to run notebooks on a kubeflow server, but after a month or two I had added too many packages and wanted to rebuild it from scratch to fix it a bit.

I noticed that the rapidsai/rapidsai images were deprecated, so I tried using rapidsai/notebooks:23.08-cuda11.8-py3.10 instead. I simply replaced the old image name with the new one.

Unfortunately the notebook server no longer works, giving me the error: Sorry, /notebook/martin/rapids-clustering-only-newimage is not a valid page - ie it's not finding the jupyter server. What do I need to change?

**Comment by rafaelvanbelle** [comment]
+1 same issue here. I was trying the new rapidsai docker notebooks image on Kubeflow and the jupyter lab page wouldn't load. Same error message as @MartinKlefas.

In the meantime, as a temporary fix, I use version 23.08 runtime docker images which seem to run fine. 
([https://hub.docker.com/r/rapidsai/rapidsai/tags](https://hub.docker.com/r/rapidsai/rapidsai/tags))

**Comment by raydouglass** [comment]
@MartinKlefas Thanks for reporting this issue. I'm not too familiar with Kubeflow, so I've pinged some other RAPIDS folks for help.

If you have any of the start up logs for running the image, that might be helpful for debugging.

**Comment by hcho3** [comment]
I was able to reproduce the issue on a fresh GKE cluster. It appears that the Jupyter server is launched at a wrong URL endpoint.

Log from the notebook pod, when launched with 23.08 runtime Docker container
```
[I 2023-09-07 20:40:44.449 ServerApp] Serving notebooks from local directory: /home/jovyan
[I 2023-09-07 20:40:44.449 ServerApp] Jupyter Server 2.7.0 is running at:
[I 2023-09-07 20:40:44.449 ServerApp] http://rapids2-0:8888/notebook/kubeflow-user-example-com/rapids2/lab
[I 2023-09-07 20:40:44.449 ServerApp]     http://127.0.0.1:8888/notebook/kubeflow-user-example-com/rapids2/lab
[I 2023-09-07 20:40:44.449 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
```

Log from the notebook pod, when launched with 23.10 notebook Docker container
```
[I 2023-09-07 20:40:53.614 ServerApp] Serving notebooks from local directory: /home/rapids/notebooks
[I 2023-09-07 20:40:53.614 ServerApp] Jupyter Server 2.7.1 is running at:
[I 2023-09-07 20:40:53.614 ServerApp] http://rapids-0:8888/lab
[I 2023-09-07 20:40:53.614 ServerApp]     http://127.0.0.1:8888/lab
[I 2023-09-07 20:40:53.614 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
```

**Comment by MartinKlefas** [comment]
Thank you @hcho3, my logs look the same.

**Comment by hcho3** [comment]
https://github.com/rapidsai/docker/blob/b1b5ab09b132b80a513626c85d7fe56e3f6710e4/Dockerfile#L87

This line should be updated to add `NotebookApp.base_url` option:

https://github.com/rapidsai/docker/blob/95beace0a9cd2f2de2f041dcac7d059692949dca/context/source_entrypoints/runtime_devel.sh#L18

**Comment by raydouglass** [comment]
Thanks @hcho3! I've opened a PR: #588

**Comment by MartinKlefas** [comment]
Hi I just pulled this image from docker hub again and it's still not working - does the fix only apply to new images?

**Comment by MartinKlefas** [comment]
Also, the notebook image `notebooks:23.10a-cuda11.8-py3.9` seems to mount very oddly in KubeFlow.
I've set it to use my old volume as it's home, but instead it's using what seems to be an internal volume:
![Root folder of the new image](https://github.com/rapidsai/docker/assets/12558370/adb8d7d8-bcf8-4806-8dea-902bcb6028a7)
The root folder should look like this:
![Root folder of ](https://github.com/rapidsai/docker/assets/12558370/0a44416f-1a2a-4516-bee1-e5c3459a6f9b)
