### ISSUE TITLE
Cannot open Jupyter Notebooks in Docker installation

### ISSUE THREAD

**Issue by boris-dee** [rapidsai/docker#62]
Hi everyone,

I'm using the docker version of rapids. I have successfully pulled the image and run it. However, there's no jupyter notebook available. I tried to run `./utils/start_jupyter.sh` and I get this:

```
jupyter-lab --allow-root --ip=0.0.0.0 --no-browser --NotebookApp.token=''

[W 17:40:04.014 LabApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[I 17:40:04.014 LabApp] The port 8888 is already in use, trying another port.
[I 17:40:04.743 LabApp] JupyterLab extension loaded from /opt/conda/envs/rapids/lib/python3.6/site-packages/jupyterlab
[I 17:40:04.743 LabApp] JupyterLab application directory is /opt/conda/envs/rapids/share/jupyter/lab
[I 17:40:04.920 LabApp] Serving notebooks from local directory: /rapids/notebooks
[I 17:40:04.920 LabApp] The Jupyter Notebook is running at:
[I 17:40:04.920 LabApp] http://4434ae38bd85:8889/
[I 17:40:04.920 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
```
However, when I click on the http link, it doesn't reach anything. I feel that this has something to do with the fact that it says `The port 8888 is already in use, trying another port.`, which I find strange because it shouldn't be already used.

**Comment by ajschmidt8** [comment]
@boris-dee, can you confirm that this is still an issue? I'm not able to replicate it on my end. can you share the exact `docker run` command that you're using to run the container? 

i.e.: 
```sh
docker run \
    --gpus all \
    --rm \
    -it \
    -p 8888:8888 -p 8787:8787 -p 8786:8786 \
    rapidsai/rapidsai-nightly:0.15-cuda10.1-runtime-ubuntu18.04-py3.7
```

**Comment by boris-dee** [comment]
@ajschmidt8, I started from scratch and just pulled the `rapidsai/rapidsai:cuda10.0-runtime-ubuntu18.04-py3.6` image.

Then:
```
docker run \
>     --gpus all \
>     --rm \
>     -it \
>     -p 8888:8888 -p 8787:8787 -p 8786:8786 \
>     rapidsai/rapidsai:cuda10.0-runtime-ubuntu18.04-py3.6
(rapids) root@b91e1bff074c:/rapids/notebooks#
```
From here nothing happens, so I opened manually my browser at the following address: `http://localhost:8888/` and jupyter opened correctly. 

So I guess it works now. What is a bit disturbing is that there's no message whatsoever, as there usually is when opening jupyter. One has to open the browser and and manually type `localhost:8888` in the address bar.

**Comment by ajschmidt8** [comment]
@boris-dee, can you pull the latest image from Docker hub and try again? We recently added some console output to specify that a jupyter-server is running. See the screenshot below.

![image](https://user-images.githubusercontent.com/7400326/89922015-7b7fb600-dbcc-11ea-8584-c0c3f3f5608b.png)

**Comment by ajschmidt8** [comment]
@boris-dee, it looks like you pulled the latest stable version. If you pull the nightly, you should see the output above. This output will be in our next stable release.

**Comment by ajschmidt8** [comment]
Closing this issue since it seems to be resolved now, though feel free to open a new issue or reply here with any other questions.

**Comment by theBull** [comment]
For some reason, on a Mac, after running the jupyter in the docker container, what worked for me was `http://mac-mini.home:8888` instead of `localhost`. "Mac-mini.home" happens to be the name of my machine, or what is returned when running `hostname` in a terminal. So using the output of `hostname` instead of `localhost` in my browser fixed the issue for me. I'd rather figure out where in the jupyter config this can be overridden, because it's not intuitive, nor does it match the feedback I'm seeing on multiple sites like stackoverflow and github.
