### ISSUE TITLE
[BUG] GPU Dashboards blank on dev container due to old jupyterlab-nvdashboard version

### ISSUE THREAD

**Issue by arnoldrw** [rapidsai/docker#67]
**Describe the bug**
The current rapids nightly docker + dev container pulled with
docker pull rapidsai/rapidsai-dev:0.12-cuda10.0-devel-ubuntu18.04-py3.7
docker run --gpus all --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786 \
    rapidsai/rapidsai-dev:0.12-cuda10.0-devel-ubuntu18.04-py3.7

I using an old version of jupyterlab-nvdashboard that causes the gpu dashboards to be blank. 

Updating the version resolves the issue. This guidance was given in this issue:
https://github.com/rapidsai/jupyterlab-nvdashboard/issues/24#issuecomment-604482425
and the resolution steps came from this issue:
https://github.com/rapidsai/jupyterlab-nvdashboard/issues/49

**Steps/Code to reproduce bug**
Run the container using
```
docker pull rapidsai/rapidsai-dev:0.12-cuda10.0-devel-ubuntu18.04-py3.7
docker run --gpus all --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786 \
    rapidsai/rapidsai-dev:0.12-cuda10.0-devel-ubuntu18.04-py3.7
```
And go to any of the gpu dashboards, they will be blank. 
**Expected behavior**
The gpu dashboards show the expected output. 

**Additional context**
Testing was done on a dgx station.

**Comment by ajschmidt8** [comment]
@arnoldrw, apologies for the late response here. it appears that our containers now have the latest version of `jupyterlab-nvdashboard` and therefore I was not able to replicate the issue at this time. I will close the issue now, but feel free to reply if you're still exhibiting the problem and we can open it back up.
