### ISSUE TITLE
[DOC] README.md needs to include examples

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/docker#9]
## Report needed documentation

**Report needed documentation**
README.md needs to add a section containing common examples with descriptions of what they do.  Without these, users may have a harder time understanding what command and/or option they should use.

**Describe the documentation you'd like**
A section in README.md, possibly just called "examples", that describes at least the following:
* How to use buildDockerImage with one of the default templates, where the resulting files go, and what steps are automated.
* How to use genBuildScript.sh to get a build.sh for building locally.
* How to change the config to build a specific set of RAPIDS components.
* How to change the config to update the version of a specific dependency.
* How to create a new Dockerfile template and use it.

**Steps taken to search for needed documentation**
Reviewers pointed out that this was needed.

**Comment by ajschmidt8** [comment]
closing this issue as it no longer appears to be applicable
