### ISSUE TITLE
[BUG] - Jupyter lab is not started after new release

### ISSUE THREAD

**Issue by vinayakbhadage** [rapidsai/docker#94]
**Describe the bug**
Jupyter lab is not started after new release

**Steps/Code to reproduce bug**
We are using the https://github.com/rapidsai/helm-chart . it was working fine but  after new release it is not working. It was using  following images:
 image:
      repository: "rapidsai/rapidsai"
      tag: cuda10.0-runtime-ubuntu16.04
Start command is : 
     - bash
      - '/rapids/notebooks/utils/start-jupyter.sh'

Even after changing path to new utils it is not working:
 - bash
      - '/rapids/utils/start-jupyter.sh'

**Expected behavior**
Rapids Helm package should work with rapidsai docker image.

**Environment details (please complete the following information):**
-using the Azure Kubernetics service for deploying with gpu instances.
 

**Additional context**

**Comment by ajschmidt8** [comment]
@vinayakbhadage, apologies for the late reply here. can you confirm whether or not this is still an issue?

**Comment by ajschmidt8** [comment]
Closing issue due to no response from author.
