### ISSUE TITLE
[BUG] Docker images do not start the RAPIDS conda env when used with `docker exec`

### ISSUE THREAD

**Issue by mike-wendt** [rapidsai/docker#95]
@rlratzel reported:

`docker run` to start an interactive bash shell, or to run an individual command, automatically executes in the `rapids` conda env.  However, when a container is started with `--detach` and has commands executed in it with `docker exec`, the commands do not run in the `rapids` conda env.

This affects jobs using the Jenkins Docker plugin.
The workaround is to issue a `source /opt/conda/bin/activate rapids` command in the script they define in order to use packages in the `rapids` env.

**Comment by ajschmidt8** [comment]
This issue seems to be resolved in #127. closing
