### ISSUE TITLE
[FEA] Add info message to container entrypoint

### ISSUE THREAD

**Issue by mike-wendt** [rapidsai/docker#96]
From @miguelangel :

> Just a quick observation about changes from 0.8 to 0.9 container.
More specifically, I have noticed that, from 0.9 container, a JupyterLab instance is executed when docker run the container.
That is very handy, but as a side effect, it took me a while to understand why local mapped folder was not visible anymore.
As a quick workaround, I have mapped my folder to /rapids/notebook, to make it visible to JupyterLab.
>> docker run --runtime=nvidia --rm -it -v /raid/miguelm:/rapids/notebooks/miguelm  -p 8888:8888 -p 8787:8787 -p 8786:8786  nvcr.io/nvidia/rapidsai/rapidsai:0.9-cuda10.0-runtime-ubuntu18.04

> Might I suggest to explicitly mention the above somewhere? Apologies if it is already detailed somewhere, but I couldn't find it.

> What about an echo message when running the container?

@rmccorm4 added:

> ...NGC DL containers have some common info they output at entrypoint - something like this might be a good place to put that

**Comment by aleksficek** [comment]
I'll work on this, similar of an recent issue I fixed https://github.com/rapidsai/docker/pull/122
